### PR TITLE
changed colors to match request

### PR DESCRIPTION
**Pull request by krzysiekh**
If it's not the way you want let me know :)

### CODE REVIEW

**Review by shreeshylahs — COMMENTED** [review]
how can just a color change has **+16164 lines** of change !?

**Comment by abhaymaniyar** [comment]
I am curious too @shreeshylahs. @krzysiekh can you please make the changes simpler?

**Comment by shreeshylahs** [comment]
it seems the commit was not clean. try ditching the PR and commit. Redo a fresh one

**Comment by krzysiekh** [comment]
Hi, 
I reckon it's because the min.css was unminified :) I changed 2 hex values.

**Comment by shreeshylahs** [comment]
oh ok cool

**Comment by abhaymaniyar** [comment]
Create a new PR with appropriate minified css with modified hex values. I will merge that. :smile: Closing this one for now.

**Pull request closed without merging**
